sudo: required
services:
  - docker
  
before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true react-test npm test
  
after_success:
  - docker build -t mavihay/mclient ./client
  - docker build -t mavihay/mserver ./server
  - docker build -t mavihay/mworker ./worker
  - docker build -t mavihay/mnginx ./nginx
  #log docker client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push themh to docker hub 
  - docker push mavihay/mclient
  - docker push mavihay/mworker
  - docker push mavihay/mserver
  - docker push mavihay/mnginx
  
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-933292581552"
  bucket_path: "mdocker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master